const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=readFileSync('src/orchid_studio/studio.js','utf8');
const snippet=source.slice(source.indexOf('function showOrchidConnection('),source.indexOf('let lastStudioResponse='));
const elements={};
const context={$:id=>elements[id]??=( {textContent:'',className:'',title:''} )};
vm.createContext(context);vm.runInContext(snippet,context);
context.showOrchidConnection({connected:true,input:'Orchid'});
assert.equal(elements['orchid-connection-label'].textContent,'ORCHID CONNECTED');
context.showOrchidConnection({connected:false,input:'Orchid'});
assert.equal(elements['orchid-connection-label'].textContent,'ORCHID DISCONNECTED');
assert.match(elements['orchid-connection-detail'].textContent,/Enable USB MIDI/);
context.showOrchidConnection({connected:null,error:'Inventory unavailable'});
assert.equal(elements['orchid-connection-label'].textContent,'CHECKING ORCHID');
context.showOrchidConnection({connected:true},true);
assert.equal(elements['orchid-connection-label'].textContent,'STUDIO OFFLINE');
assert.match(elements['orchid-connection'].className,/unknown/);
console.log('Connection badge: connected, disconnected, unknown and offline passed');
