// The grid is a draft. Save publishes atomically; playing beats switch on the next bar.
let draft=null,soundBank={sounds:[],kits:[]},editBar=0,history=[];
function editNotice(text){$('edit-state').textContent=text}
function remember(){history.push(JSON.stringify(draft));if(history.length>40)history.shift();editNotice('Unsaved changes')}
function downloadJSON(document,name){const url=URL.createObjectURL(new Blob([JSON.stringify(document,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function soundRefresh(){soundBank=await command({command:'kits-list'});$('sound-count').textContent=`${soundBank.sounds.length} sounds · ${soundBank.kits.length} kits`;const list=$('kit-library');list.replaceChildren();for(const kit of soundBank.kits){const p=document.createElement('p');p.className='small';p.textContent=`${kit.name} · ${kit.sounds.length} sounds · ${kit.author} · ${kit.license}`;list.append(p)}}
function soundSelect(value){const select=document.createElement('select');for(const kit of soundBank.kits){const group=document.createElement('optgroup');group.label=kit.name;for(const sound of soundBank.sounds.filter(s=>s.kit===kit.id)){const o=document.createElement('option');o.value=sound.id;o.textContent=sound.name;group.append(o)}select.append(group)}select.value=value;return select}
function renderEditor(){if(!draft)return;$('beat-name').value=draft.name;$('beat-bars').value=draft.bars;$('beat-swing').value=draft.swing;$('edit-bar').replaceChildren();for(let i=0;i<draft.bars;i++){const o=document.createElement('option');o.value=i;o.textContent='Bar '+(i+1);$('edit-bar').append(o)}editBar=Math.min(editBar,draft.bars-1);$('edit-bar').value=editBar;
const grid=$('drum-grid');grid.replaceChildren();const head=document.createElement('div');head.className='drum-row';const corner=document.createElement('span');corner.textContent='Sound / lane';head.append(corner);for(let i=0;i<16;i++){const n=document.createElement('span');n.className='step-label';n.textContent=i%4===0?String(i/4+1):['','e','&','a'][i%4];head.append(n)}grid.append(head);
for(const lane of draft.lanes){const row=document.createElement('div');row.className='drum-row';const controls=document.createElement('div');controls.className='lane-controls';const title=document.createElement('span');title.textContent=lane.name;title.className='small';const select=soundSelect(lane.sound);select.setAttribute('aria-label',lane.name+' sound');select.onchange=()=>{remember();lane.sound=select.value};const buttons=document.createElement('div');buttons.className='lane-buttons';const preview=document.createElement('button');preview.textContent='▶';preview.setAttribute('aria-label','Preview '+lane.name);preview.onclick=()=>action(()=>command({command:'sound-preview',sound:lane.sound}));const mute=document.createElement('button');mute.textContent=lane.muted?'Unmute':'Mute';mute.setAttribute('aria-label','Mute '+lane.name);mute.onclick=()=>{remember();lane.muted=!lane.muted;renderEditor()};const gain=document.createElement('input');gain.type='number';gain.min=0;gain.max=1.5;gain.step=.1;gain.value=lane.gain;gain.title='Lane volume';gain.setAttribute('aria-label',lane.name+' volume');gain.onchange=()=>{remember();lane.gain=Number(gain.value)};buttons.append(preview,mute,gain);controls.append(title,select,buttons);row.append(controls);
for(let step=0;step<16;step++){const beat=editBar*4+step/4;const hits=draft.hits.filter(h=>h.lane===lane.id&&h.beat>=beat-1e-8&&h.beat<beat+.25-1e-8);const hit=hits[0];const btn=document.createElement('button');btn.className='drum-step'+(step%4===0?' downbeat':'')+(hit?' filled':'')+(hit?.velocity>=.75?' accent':'');btn.setAttribute('aria-label',`${lane.name}, bar ${editBar+1}, step ${step+1}`);btn.setAttribute('aria-pressed',String(!!hit));btn.title=hit?`${Math.round(hit.velocity*100)}% velocity · ${Math.round((hit.probability??1)*100)}% chance${Math.abs(hit.beat-beat)>.001?' · offset timing preserved':''}. Shift-click: accent`:'Click to add. Shift-click: accent';btn.textContent=hit?(hit.velocity>=.75?'●':'•'):'';btn.onclick=e=>{remember();if(hit&&e.shiftKey){hit.velocity=hit.velocity>=.75?.55:.9}else if(hit){draft.hits=draft.hits.filter(h=>!hits.includes(h))}else{draft.hits.push({lane:lane.id,beat,velocity:e.shiftKey?.9:Number($('hit-velocity').value),probability:Number($('hit-chance').value)})}renderEditor()};row.append(btn)}grid.append(row)}
$('beat-editor').hidden=false}
async function editSelected(){await soundRefresh();draft=(await command({command:'beat-get',beat:$('beats').value})).document;draft.id='user-'+Date.now().toString(36);draft.name+=' variation';history=[];editBar=0;renderEditor();editNotice('Editing a copy · original stays in your library');$('beat-editor').scrollIntoView({behavior:'smooth',block:'start'})}
async function refreshBeatList(selected){drumPreviewKey='';const response=await command({command:'beats-list'});cap.beats=response.beats;$('beats').replaceChildren();for(const b of cap.beats){const o=document.createElement('option');o.value=b.id;o.textContent=b.name+' · '+b.genre;$('beats').append(o)}if(selected)$('beats').value=selected;beatInfo()}
$('edit-beat').onclick=()=>action(async()=>{await editSelected();return {status:'ok'}});
$('new-beat').onclick=()=>action(async()=>{await soundRefresh();const template=(await command({command:'beat-get',beat:'glass-house'})).document;draft={...template,id:'user-'+Date.now().toString(36),name:'My new beat',genre:'custom',hits:[],swing:0};history=[];editBar=0;renderEditor();editNotice('Blank 12-bar beat · click steps to add hits');$('beat-editor').scrollIntoView({behavior:'smooth'});return {status:'ok'}});
$('beat-name').oninput=()=>{if(draft){remember();draft.name=$('beat-name').value}};
$('beat-bars').onchange=()=>{if(!draft)return;const bars=Number($('beat-bars').value);if(!Number.isInteger(bars)||bars<2||bars>64||bars%2){$('beat-bars').value=draft.bars;return}remember();const oldBars=draft.bars,oldHits=draft.hits;draft.bars=bars;draft.hits=[];for(let offset=0;offset<bars*4;offset+=oldBars*4)for(const hit of oldHits)if(hit.beat+offset<bars*4)draft.hits.push({...hit,beat:hit.beat+offset});renderEditor()};
$('beat-swing').oninput=()=>{if(draft){remember();draft.swing=Number($('beat-swing').value)}};
$('edit-bar').onchange=()=>{editBar=Number($('edit-bar').value);renderEditor()};
$('copy-all-bars').onclick=()=>{if(!draft)return;remember();const hits=draft.hits.filter(h=>h.beat>=editBar*4&&h.beat<(editBar+1)*4);draft.hits=[];for(let bar=0;bar<draft.bars;bar++)for(const h of hits)draft.hits.push({...h,beat:h.beat-editBar*4+bar*4});renderEditor()};
$('copy-next-bar').onclick=()=>{if(!draft)return;remember();const next=(editBar+1)%draft.bars;const hits=draft.hits.filter(h=>h.beat>=editBar*4&&h.beat<(editBar+1)*4);draft.hits=draft.hits.filter(h=>h.beat<next*4||h.beat>=(next+1)*4);for(const h of hits)draft.hits.push({...h,beat:h.beat-editBar*4+next*4});editBar=next;renderEditor()};
$('clear-bar').onclick=()=>{if(!draft)return;remember();draft.hits=draft.hits.filter(h=>h.beat<editBar*4||h.beat>=(editBar+1)*4);renderEditor()};
$('beat-undo').onclick=()=>{if(history.length){draft=JSON.parse(history.pop());renderEditor();editNotice('Undone · save to apply')}};
$('add-lane').onclick=()=>{if(!draft||draft.lanes.length>=32||!soundBank.sounds.length)return;remember();const id='lane-'+Date.now().toString(36);draft.lanes.push({id,name:'Extra '+(draft.lanes.length+1),sound:soundBank.sounds[0].id,gain:1,muted:false});renderEditor()};
$('save-beat').onclick=()=>action(async()=>{draft.name=$('beat-name').value;const r=await command({command:'beat-save',document:draft});draft=r.document;await refreshBeatList(draft.id);beatDirty=true;editNotice(r.status==='queued'?'Saved · update on next bar':'Saved to your local library');return r});
$('export-beat').onclick=()=>{if(draft)downloadJSON(draft,draft.id+'.json')};
$('import-beat').onclick=()=>$('beat-file').click();$('beat-file').onchange=()=>action(async()=>{const f=$('beat-file').files[0];if(!f)return {status:'ok'};if(f.size>1048576)throw Error('Beat JSON must be under 1 MB');const d=JSON.parse(await f.text());const r=await command({command:'beat-save',document:d});draft=r.document;await soundRefresh();await refreshBeatList(draft.id);renderEditor();editNotice('Imported and saved');return r});
$('import-kit').onclick=()=>action(async()=>{const r=await command({command:'kits-import',path:$('kit-path').value});await soundRefresh();renderEditor();return r});
$('upload-sample').onclick=()=>$('sample-file').click();$('sample-file').onchange=()=>action(async()=>{const file=$('sample-file').files[0];if(!file)return {status:'ok'};if(file.size>8*1024*1024)throw Error('Use a PCM WAV under 8 MB and 30 seconds');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const r=await command({command:'sample-upload',name:file.name.replace(/\.wav$/i,''),data});await soundRefresh();renderEditor();return r});
soundRefresh().catch(()=>{});
