const TEMPO_MIN=60,TEMPO_MAX=200;
function boundTempo(value){return Math.max(TEMPO_MIN,Math.min(TEMPO_MAX,Math.round(value)))}
const colors=['#b7a25b','#86a47b','#cf7856','#87a8a0'];
const paths={play:'<path d="M8 5v14l11-7z" fill="currentColor" stroke="none"/>',pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',stop:'<rect x="6" y="6" width="12" height="12" rx="1" fill="currentColor" stroke="none"/>',record:'<circle cx="12" cy="12" r="7" fill="currentColor" stroke="none"/>',sound:'<path d="M4 8h16M4 16h16M8 5v6M16 13v6"/>',speaker:'<path d="M4 9h4l5-4v14l-5-4H4zM17 8q5 4 0 8"/>',muted:'<path d="M4 9h4l5-4v14l-5-4H4zM17 9l5 6M22 9l-5 6"/>',select:'<path d="m5 12 4 4L19 6"/>',undo:'<path d="M4 10h10a6 6 0 0 1 0 12M4 10l5-5M4 10l5 5" transform="translate(0 -3)"/>',trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 10v7M14 10v7"/>',save:'<path d="M5 3h12l3 3v15H4V3zM8 3v6h8V3M8 21v-7h8v7"/>',import:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',cancel:'<path d="m6 6 12 12M18 6 6 18"/>',together:'<path d="M4 5v14l8-7z" fill="currentColor"/><path d="M17 6v12M14 9h6M14 15h6"/>'};
function icon(name){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[name]+'</svg>'}

let state=null,cap=null,dirty=false,beatDirty=false,tempoEditing=false;
let pistilCatalog=[];
let drumPreview=null,drumPreviewKey='';
const $=id=>document.getElementById(id);
const labels={bpm:'Studio BPM',mode:'Perform mode',step_beats:'Step length · beats',gate:'Note gate',velocity_limit:'Velocity limit',spread_beats:'Sweep spread · beats',harp_octaves:'Harp octaves',slop:'Slop amount',seed:'Slop seed',pattern:'Perform rhythm',chord_window_ms:'Chord grouping · ms'};
async function command(data){const response=await fetch('/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(result.status==='error')throw Error(result.error);return result}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}
function values(){const result={};for(const [key,schema] of Object.entries(cap.settings_schema.properties)){const v=$('setting-'+key).value;result[key]=schema.type==='string'?v:Number(v)}return result}
function fill(config){for(const [key,value] of Object.entries(config))if(key!=='bpm'&&$('setting-'+key)&&document.activeElement!==$('setting-'+key))$('setting-'+key).value=value}
function beatInfo(){const beat=cap.beats.find(b=>b.id===$('beats').value);$('beat-info').textContent=beat?`${beat.name} · ${beat.bars} bars · ${beat.genre} · ${beat.vibe||beat.feel} · suggested ${beat.suggested_bpm} BPM${beat.energy?' · '+beat.energy+' energy / '+beat.density+' density':''}${beat.best_for?' · Good for: '+beat.best_for:''}`:''}
function showLoops(){
 const instruments=state.instruments,l=state.looper;if(!l)return;
 $('pistil-state').textContent=instruments.enabled?(instruments.error?'Audio error: '+instruments.error:'Four loops + Perform + Play Along'):'Native audio required for the mixer';
 $('pistil-enable').textContent=instruments.error?'Restart audio':'Enable audio';$('pistil-enable').disabled=(instruments.enabled&&!instruments.error)||state.playing;
 const length=l.settings.bars*4,paused=state.tempo?.paused;
 $('loop-status').textContent=l.error?'Error: '+l.error:(paused?'Paused':l.phase==='count-in'?`Count-in · ${Math.ceil(-l.beat)} beats`:l.phase==='armed'?`Layer ${l.record_slot} armed · ${Math.ceil(l.beats_until_record)} beats`:l.phase==='recording'?`Recording layer ${l.record_slot}`:l.running?'Playing':'Stopped')+` / BAR ${Math.floor((l.running?l.position:0)/4)+1} OF ${l.settings.bars}`;
 $('loop-progress').max=length;$('loop-progress').value=l.position;
 const track=$('loop-track');if(track.children.length!==length){track.replaceChildren();for(let i=0;i<length;i++){const cell=document.createElement('span');cell.className='loop-cell'+(i%4===0?' downbeat':'');track.append(cell)}}
 for(let i=0;i<track.children.length;i++)track.children[i].classList.toggle('active',l.running&&!paused&&l.beat>=0&&Math.floor(l.position)===i);
 for(const layer of l.layers){const slot=layer.slot;$('layer-info-'+slot).textContent=layer.note_count+' NOTES';const soundSelect=$('layer-sound-'+slot),presetMatch=/^Sound (\d+)$/.exec(instruments.labels[slot-1]||'');if(document.activeElement!==soundSelect)soundSelect.value=presetMatch?Number(presetMatch[1]):'';soundSelect.disabled=!instruments.enabled||!!instruments.error;$('layer-mode-'+slot).textContent=layer.mode||'Empty / ready to record';$('layer-card-'+slot).classList.toggle('selected',Number($('loop-slot').value)===slot);$('layer-editor-'+slot).disabled=!instruments.enabled;
 const btn=$('layer-mute-'+slot);btn.innerHTML=icon(layer.muted?'muted':'speaker');btn.setAttribute('aria-label',(layer.muted?'Unmute':'Mute')+' layer '+slot);btn.title=(layer.muted?'Unmute':'Mute')+' layer '+slot;btn.setAttribute('aria-pressed',String(layer.muted));
 $('layer-clear-'+slot).disabled=!!l.record_slot||!layer.note_count;$('layer-clear-'+slot).title=l.record_slot?'Finish or cancel the take before clearing':'Clear layer '+slot+' notes (keeps sound; Stop then Undo to restore)';
 $('layer-record-'+slot).classList.toggle('active',l.record_slot===slot);$('layer-record-'+slot).disabled=!!l.record_slot;
 }
 drawLoops(l);
 for(const id of ['loop-bars','loop-grid','loop-count','loop-step','loop-undo','loop-open'])$(id).disabled=l.running;
 if(l.running){$('loop-bars').value=l.settings.bars;$('loop-grid').value=l.settings.grid;$('loop-count').value=l.settings.count_in;}
 $('loop-drums').disabled=l.running;
 $('key-start').checked=!!l.start_on_key;$('key-start').disabled=!!l.record_slot;
 if(l.waiting_for_key)$('loop-status').textContent='WAITING FOR KEY';
 $('loop-cancel').disabled=!l.record_slot;$('loop-record').disabled=!!l.record_slot||!!paused;$('loop-undo').disabled=l.running||!l.undo_available;
 $('pause').disabled=!state.playing||!!l.record_slot;$('pause').innerHTML=icon(paused?'play':'pause');$('pause').title=paused?'Resume playback':'Pause playback';$('pause').setAttribute('aria-label',$('pause').title);
 const beat=Math.max(0,state.tempo?.beat||0);$('transport-position').textContent=String(Math.floor(beat/4)%l.settings.bars+1).padStart(2,'0')+' : '+String(Math.floor(beat%4)+1).padStart(2,'0');$('transport-mode').textContent=l.waiting_for_key?'WAITING FOR KEY':paused?'PAUSED':l.record_slot?'RECORDING':l.running?'LOOPS':state.performance?'LIVE':state.playing?'DRUMS':'READY TO PLAY';
 for(const cell of $('drum-pulse').children)cell.classList.toggle('active',state.playing&&!paused&&state.drums.playing_requested&&Number(cell.dataset.step)===Math.floor(beat*4)%16);
}
async function refresh(){state=await command({command:'status'});$('status').textContent=state.looper?.waiting_for_key?'Waiting for key':state.tempo?.paused?'Paused':state.playing?'Playing':'Connected';$('bank').textContent=state.drums.bank_load_requested?'SOUNDS READY':'SOUNDS NOT LOADED';$('raw').textContent=JSON.stringify(state,null,2);showLoops();showMixer();showPlaybackButtons();showPistilSelector();showDrumSequence();$('clock-summary').textContent=state.midi_clock.enabled?'MIDI CLOCK OUT':'INTERNAL MASTER';$('beat-tempo').disabled=state.playing;if(state.midi_clock){const c=state.midi_clock;$('clock-state').textContent=c.error?'Clock error: '+c.error:c.enabled?`${c.port} · 24 PPQN · ${c.running?'running':'ready'} · ${c.pulses_sent} pulses`:'Clock output off';$('clock-apply').disabled=state.playing}$('sound-state').textContent=state.sound_follow.enabled?'Sound dial: '+state.sound_follow.status+(state.sound_follow.last_preset?' · preset '+state.sound_follow.last_preset:''):'Sound dial following off';if(!dirty)fill(state.performance?.settings||state.performance_defaults);syncDial();if(!tempoEditing&&document.activeElement!==$('setting-bpm'))$('setting-bpm').value=state.tempo.target_bpm??state.tempo.bpm;syncTempoDial();$('tempo-transition').textContent=state.tempo.transitioning?state.tempo.bpm.toFixed(1)+' → '+state.tempo.target_bpm+' BPM':'2 SEC · SMOOTH';if(!beatDirty&&state.drums.beat){$('beats').value=state.drums.beat;beatInfo()}}
async function action(fn){try{const result=await fn();await refresh();message(result.status==='queued'?'Queued for the next bar.':'');}catch(error){message(error.message,true)}}
function perform(drums){return {command:'perform',input:$('input').value,chord_channel:Number($('chord').value),output_channel:Number($('output').value),settings:values(),...(drums?{drums:{engine:'studio',beat:$('beats').value,volume:Number($('volume').value)}}:{})}}
async function init(){try{cap=await command({command:'capabilities'});for(const key of ['mode','pattern','step_beats','gate','velocity_limit','spread_beats','harp_octaves','slop','seed','chord_window_ms']){const schema=cap.settings_schema.properties[key],label=document.createElement('label');label.textContent=labels[key];const input=document.createElement(schema.enum?'select':'input');input.id='setting-'+key;if(schema.enum){for(const value of schema.enum){const option=document.createElement('option');option.value=value;option.textContent=value;input.append(option)}}else{input.type='number';input.min=schema.minimum;input.max=schema.maximum;input.step=schema.type==='integer'?'1':'any'}input.value=schema.default;if(['mode','pattern','step_beats'].includes(key))label.hidden=true;input.required=true;input.addEventListener('input',()=>dirty=true);label.append(input);$('settings').append(label)}for(const beat of cap.beats){const option=document.createElement('option');option.value=beat.id;option.textContent=beat.name+' · '+beat.genre;$('beats').append(option)}setupDial();await loadPistilCatalog();beatInfo();await refresh();if(state.midi_clock){$('clock-enabled').checked=state.midi_clock.enabled;$('clock-offset').value=state.midi_clock.offset_ms}if(state.instruments?.enabled&&state.instruments.selected_slot<=4)$('loop-slot').value=state.instruments.selected_slot;if(state.looper){$('loop-bars').value=state.looper.settings.bars;$('loop-grid').value=state.looper.settings.grid;$('loop-count').value=state.looper.settings.count_in}setInterval(()=>refresh().catch(e=>message(e.message,true)),250)}catch(e){message(e.message,true)}}
$('beats').onchange=()=>{beatDirty=true;beatInfo()};
$('performance').onsubmit=e=>{e.preventDefault();applyPerform()};
$('live').onclick=()=>action(()=>togglePlayback('live',async()=>{if(state.playing)await command({command:'stop'});const r=await command(perform(false));dirty=false;return r}));
$('together').onclick=()=>action(()=>togglePlayback('together',async()=>{if(state.playing)await command({command:'stop'});const r=await command(perform(true));dirty=false;return r}));
$('load').onclick=()=>action(()=>command({command:'beats-load'}));
$('select').onclick=()=>action(async()=>{const r=await command({command:'beats-select',beat:$('beats').value});beatDirty=false;return r});
$('drums').onclick=()=>action(()=>togglePlayback('drums',async()=>{if(state.playing)await command({command:'stop'});const r=await command({command:'beats-play',beat:$('beats').value,bpm:values().bpm,volume:Number($('volume').value)});beatDirty=false;return r}));
$('beat-tempo').onclick=()=>action(async()=>{const beat=cap.beats.find(b=>b.id===$('beats').value);const r=await command({command:'tempo',bpm:beat.suggested_bpm});$('setting-bpm').value=beat.suggested_bpm;return r});
$('mix').onclick=()=>action(()=>command({command:'drums',action:'volume',value:Number($('volume').value)}));
$('sound-on').onclick=()=>action(()=>command({command:'sound-follow',input:$('input').value,enabled:true}));
$('sound-off').onclick=()=>action(()=>command({command:'sound-follow',enabled:false}));
$('clock-apply').onclick=()=>action(()=>command({command:'clock-configure',enabled:$('clock-enabled').checked,offset_ms:Number($('clock-offset').value)}));
$('stop').onclick=()=>action(()=>command({command:'stop'}));
$('panic').onclick=()=>action(()=>command({command:'panic'}));
function loopConfig(){return {bars:Number($('loop-bars').value),grid:Number($('loop-grid').value),count_in:Number($('loop-count').value)}}
async function loopStart(record){if(state.tempo.paused&&state.looper.running&&!record)return command({command:'resume'});if(state.playing&&!state.looper.running)await command({command:'stop'});await command({command:'layer-select',slot:Number($('loop-slot').value)});if(state.looper.running){if(!record)return {status:'ok'};return command({command:'loop-record',slot:Number($('loop-slot').value),settings:values()})}await command({command:'loop-configure',settings:loopConfig()});return command({...perform($('loop-drums').checked),command:'loop-start',...(record?{slot:Number($('loop-slot').value)}:{})})}
for(let slot=1;slot<=4;slot++){
 const card=document.createElement('div');card.className='layer';card.id='layer-card-'+slot;card.style.setProperty('--strip',colors[slot-1]);
 card.innerHTML=`<div class="layer-heading"><strong>LOOP 0${slot}</strong><span class="layer-count" id="layer-info-${slot}"></span></div><select class="sound-label" id="layer-sound-${slot}" aria-label="Sound for layer ${slot}" title="Change this layer’s sound; recorded notes stay the same"></select><span class="mode-label" id="layer-mode-${slot}"></span><svg class="preview" id="layer-preview-${slot}" viewBox="0 0 240 66" preserveAspectRatio="none" role="img" aria-label="Layer ${slot} note pattern"></svg><div class="actions"><button class="key" id="layer-select-${slot}" aria-label="Select layer ${slot}" title="Select layer ${slot}">${icon('select')}</button><button class="key" id="layer-mute-${slot}" aria-label="Mute layer ${slot}" title="Mute layer ${slot}">${icon('speaker')}</button><button class="key" id="layer-record-${slot}" aria-label="Record layer ${slot}" title="Record layer ${slot}">${icon('record')}</button><button class="key" id="layer-editor-${slot}" aria-label="Sound editor layer ${slot}" title="Sound editor layer ${slot}">${icon('sound')}</button><button class="key" id="layer-clear-${slot}" aria-label="Clear layer ${slot}" title="Clear layer ${slot} notes">${icon('trash')}</button></div>`;
 $('loop-layers').append(card);
 $('layer-select-'+slot).onclick=()=>action(async()=>{const r=await command({command:'layer-select',slot});$('loop-slot').value=slot;return r});
 $('layer-mute-'+slot).onclick=()=>action(()=>command({command:'loop-mute',slot,muted:!state.looper.layers[slot-1].muted}));
 $('layer-editor-'+slot).onclick=()=>action(async()=>{const r=await command({command:'layer-editor',slot});$('loop-slot').value=slot;return r});
 $('layer-sound-'+slot).onchange=()=>action(()=>command({command:'layer-preset',slot,preset:Number($('layer-sound-'+slot).value)}));
 $('layer-clear-'+slot).onclick=()=>action(()=>command({command:'loop-clear',slot}));
 $('layer-record-'+slot).onclick=()=>action(async()=>{$('loop-slot').value=slot;return loopStart(true)});
}
$('pistil-enable').onclick=()=>action(()=>command({command:'pistil-enable'}));$('loop-slot').onchange=()=>action(()=>command({command:'layer-select',slot:Number($('loop-slot').value)}));
$('loop-play').onclick=()=>action(()=>togglePlayback('loop-play',()=>loopStart(false)));$('loop-record').onclick=()=>action(()=>loopStart(true));
$('loop-cancel').onclick=()=>action(()=>command({command:'loop-cancel'}));$('loop-undo').onclick=()=>action(()=>command({command:'loop-undo'}));
$('loop-step').onclick=()=>action(async()=>{await command({command:'loop-configure',settings:loopConfig()});const beat=Number($('step-beat').value),duration=Number($('step-duration').value);const result=await command({command:'loop-step',slot:Number($('loop-slot').value),notes:$('step-notes').value.split(/[ ,]+/).filter(Boolean).map(Number),beat,duration,settings:values()});$('step-beat').value=(beat+duration)%(Number($('loop-bars').value)*4);return result});
$('loop-rest').onclick=()=>{$('step-beat').value=(Number($('step-beat').value)+Number($('step-duration').value))%(Number($('loop-bars').value)*4)};
$('loop-save').onclick=()=>action(async()=>{const r=await command({command:'loop-export'});const url=URL.createObjectURL(new Blob([JSON.stringify(r.document,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='orchid-loops.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return r});
$('loop-open').onclick=()=>$('loop-file').click();$('loop-file').onchange=()=>action(async()=>{const file=$('loop-file').files[0];if(!file) return {status:'ok'};if(file.size>1048576)throw Error('Loop file must be under 1 MB');const r=await command({command:'loop-import',document:JSON.parse(await file.text())});$('loop-bars').value=r.looper.settings.bars;$('loop-grid').value=r.looper.settings.grid;$('loop-count').value=r.looper.settings.count_in;fill((await command({command:'loop-export'})).document.performance);dirty=true;return r});
$('tempo-apply').onclick=()=>action(()=>{const bpm=boundTempo(Number($('setting-bpm').value));$('setting-bpm').value=bpm;syncTempoDial();return command({command:'tempo',bpm})});
$('setting-bpm').onchange=()=>$('tempo-apply').click();
$('setting-bpm').onkeydown=e=>{if(e.key==='Enter'){$('tempo-apply').click();e.target.blur()}};
$('pause').onclick=()=>action(()=>command({command:state.tempo.paused?'resume':'pause'}));
$('live-editor').onclick=()=>action(()=>command({command:'layer-editor',slot:5}));
for(const button of document.querySelectorAll('[data-icon]'))button.innerHTML=icon(button.dataset.icon);
for(let i=0;i<16;i++){const cell=document.createElement('i');cell.dataset.step=i;$('drum-pulse').append(cell)}
setupMixer();setupTempoDial();setupPistilSelector();init();

function applyPerform(){return action(async()=>{const settings=values();delete settings.bpm;const r=await command({command:state?.performance&&state.playing?'perform-update':'perform-configure',settings});dirty=false;return r})}
function dialModes(){return cap.mode_banks[$('perform-bank').value]||cap.modes}
function setDialMode(i,apply=true){const modes=dialModes();i=Math.max(0,Math.min(modes.length-1,i));$('setting-mode').value=modes[i];dirty=true;syncDial();if(apply)applyPerform()}
function renderDialBank(){const modes=dialModes();$('dial-options').replaceChildren();for(let i=0;i<modes.length;i++){const angle=(-135+i*270/(modes.length-1))*Math.PI/180;const b=document.createElement('button');b.className='dial-option';b.dataset.mode=modes[i];if(cap.melodic_modes?.[modes[i]]){b.classList.add('melodic-mode');b.title=cap.melodic_modes[modes[i]].description}b.textContent=modes[i]==='off'?'CHORD':(cap.melodic_modes?.[modes[i]]?.label||modes[i].toUpperCase());b.style.left=(130+Math.sin(angle)*112)+'px';b.style.top=(130-Math.cos(angle)*112)+'px';b.onclick=()=>setDialMode(i);$('dial-options').append(b)}$('perform-dial').setAttribute('aria-valuemax',modes.length-1)}
function syncDial(){if(!$('setting-mode'))return;const value=$('setting-mode').value;const bank=Object.keys(cap.mode_banks).find(b=>cap.mode_banks[b].includes(value));if(bank&&$('perform-bank').value!==bank){$('perform-bank').value=bank;renderDialBank()}const modes=dialModes();const index=modes.indexOf(value);const melody=cap.melodic_modes?.[value];$('perform-help').textContent=melody?melody.description+' Hold one key; release to stop.':(cap.mode_map?.[value]?.description||'Dial shapes live playing and your next take.');$('pattern-control').disabled=!!melody;$('perform-dial').style.setProperty('--angle',(-135+index*270/(modes.length-1))+'deg');$('dial-value').textContent=value==='off'?'CHORD':(melody?.label||value.toUpperCase());$('perform-dial').setAttribute('aria-valuenow',index);$('perform-dial').setAttribute('aria-valuetext',melody?.title||value);for(const b of $('dial-options').children)b.classList.toggle('active',b.dataset.mode===value);if(document.activeElement!==$('pattern-control'))$('pattern-control').value=$('setting-pattern').value;if(document.activeElement!==$('division-control'))$('division-control').value=$('setting-step_beats').value}
function setupDial(){cap.mode_banks ||= {classic:cap.modes};for(const bank of Object.keys(cap.mode_banks)){const option=document.createElement('option');option.value=bank;option.textContent=bank[0].toUpperCase()+bank.slice(1);$('perform-bank').append(option)}$('perform-bank').onchange=()=>{renderDialBank();setDialMode(0)};renderDialBank();$('perform-dial').onkeydown=e=>{const modes=dialModes();let i=modes.indexOf($('setting-mode').value);if(['ArrowRight','ArrowUp'].includes(e.key))i++;else if(['ArrowLeft','ArrowDown'].includes(e.key))i--;else if(e.key==='Home')i=0;else if(e.key==='End')i=modes.length-1;else return;e.preventDefault();setDialMode(i)};let drag=null;$('perform-dial').onpointerdown=e=>{drag={y:e.clientY,index:dialModes().indexOf($('setting-mode').value)};e.currentTarget.setPointerCapture(e.pointerId)};$('perform-dial').onpointermove=e=>{if(drag)setDialMode(drag.index+Math.round((drag.y-e.clientY)/18),false)};$('perform-dial').onpointerup=()=>{if(drag){drag=null;applyPerform()}};$('perform-dial').onpointercancel=()=>{drag=null;dirty=false;refresh()};$('pattern-control').innerHTML=$('setting-pattern').innerHTML;$('pattern-control').onchange=()=>{$('setting-pattern').value=$('pattern-control').value;applyPerform()};$('division-control').onchange=()=>{$('setting-step_beats').value=$('division-control').value;applyPerform()};syncDial()}

function setupMixer(){const channels=['layer-1','layer-2','layer-3','layer-4','drums','live','play-along'];for(const [i,channel] of channels.entries()){const label=i<4?'LOOP 0'+(i+1):channel==='play-along'?'PLAY ALONG':channel==='live'?'PERFORM':channel.toUpperCase();const strip=document.createElement('div');strip.className='mixer-strip';strip.style.setProperty('--strip',colors[i]|| (i===4?'#dd7049':'#294f40'));strip.innerHTML=`<div class="strip-name"><i class="strip-dot"></i>${label}</div><div class="fader-area"><div class="fader-scale"><span>+3</span><span>0</span><span>−12</span><span>−∞</span></div><input class="volume-fader" id="mix-volume-${channel}" type="range" min="0" max="1.5" step="0.01" value="${i===4?.3:1}" aria-label="${label} volume"></div><output class="level-value" id="mix-level-${channel}">0.0 dB</output><input class="pan-fader" id="mix-pan-${channel}" type="range" min="-1" max="1" step="0.01" value="0" aria-label="${label} pan"><div class="pan-labels"><span>L</span><output id="mix-pan-value-${channel}">C</output><span>R</span></div><div class="strip-divider"></div>`;$('mixer-strips').append(strip);if(channel==='live'){const name=strip.querySelector('.strip-name');const button=document.createElement('button');button.className='live-select';button.textContent='PERFORM';button.id='select-live';button.title='Select Live for the Orchid Sound dial';button.setAttribute('aria-label','Select live sound');name.lastChild.remove();name.append(button);button.onclick=()=>action(()=>command({command:'layer-select',slot:5}))}if(channel==='play-along'){const button=document.createElement('button');button.id='play-along-toggle';button.className='small-button';button.textContent='Enable';button.onclick=()=>action(()=>command({command:'play-along',enabled:!state.play_along.enabled,input:$('input').value,chord_channel:Number($('chord').value)}));strip.append(button)}let timer;let chain=Promise.resolve();const send=()=>{clearTimeout(timer);const volume=Number($('mix-volume-'+channel).value),pan=Number($('mix-pan-'+channel).value);chain=chain.then(()=>command({command:'mixer-set',channel,volume,pan})).then(()=>refresh()).catch(e=>message(e.message,true))};for(const kind of ['volume','pan']){const input=$('mix-'+kind+'-'+channel);input.oninput=()=>{showMixValues(channel);clearTimeout(timer);timer=setTimeout(send,100)};input.onchange=send}strip.querySelector('.pan-fader').ondblclick=e=>{e.target.value=0;showMixValues(channel);send()}}}
function showMixValues(channel){const v=Number($('mix-volume-'+channel).value),p=Number($('mix-pan-'+channel).value);$('mix-level-'+channel).textContent=v===0?'−∞ dB':(20*Math.log10(v)).toFixed(1)+' dB';$('mix-pan-value-'+channel).textContent=Math.abs(p)<.005?'C':(p<0?'L ':'R ')+Math.round(Math.abs(p)*100)}
function showMixer(){const direct=state.play_along||{};const toggle=$('play-along-toggle');$('play-along-help').textContent=direct.error?'Play Along: '+direct.error:'Play Along uses your keys directly while the transport runs. It follows the Orchid Sound dial.';toggle.textContent=direct.enabled?'On':'Off';toggle.setAttribute('aria-label',(direct.enabled?'Disable':'Enable')+' play along');toggle.setAttribute('aria-pressed',String(!!direct.enabled));toggle.disabled=!state.instruments.enabled||!!state.instruments.error;$('select-live').setAttribute('aria-pressed',String(state.instruments.selected_slot===5));for(const [channel,values] of Object.entries(state.mixer||{})){for(const kind of ['volume','pan']){const input=$('mix-'+kind+'-'+channel);if(!input)continue;if(document.activeElement!==input)input.value=values[kind];input.disabled=!state.instruments.enabled||!!state.instruments.error}showMixValues(channel)}$('volume').value=state.mixer.drums.volume}
function drawLoops(l){const length=l.settings.bars*4;let grid='';for(let beat=0;beat<=length;beat++){const x=beat/length*1000;grid+=`<path d="M${x} 16V180" stroke="${beat%4===0?'#667d5c':'#3b5944'}" stroke-width="${beat%4===0?1:.5}"/>`;if(beat%4===0&&beat<length)grid+=`<text x="${x+5}" y="10" fill="#aaba91" font-size="8" font-family="monospace">${beat/4+1}</text>`}for(let y=36;y<180;y+=36)grid+=`<path d="M0 ${y}H1000" stroke="#3b5944" stroke-width=".5"/>`;const all=l.layers.flatMap(x=>x.notes||[]);const low=Math.min(48,...all.map(n=>n.note)),high=Math.max(low+24,...all.map(n=>n.note));for(const layer of l.layers){const notes=layer.notes||[];const lines=(width,height,offset=0)=>notes.map(n=>{const x=n.beat/length*width,x2=Math.min(width,(n.beat+n.duration)/length*width),y=offset+(1-(n.note-low)/(high-low))*(height-offset-8)+4;return `<path d="M${x.toFixed(2)} ${y.toFixed(2)}H${x2.toFixed(2)}" stroke-width="${width===1000?2.2:1.8}" opacity="${layer.muted?.2:.4+n.velocity/180}"/>`}).join('');grid+=`<g stroke="${colors[layer.slot-1]}" stroke-linecap="round">${lines(1000,176,20)}</g>`;$('layer-preview-'+layer.slot).innerHTML=`<g stroke="${['#756634','#46704d','#a35235','#477a70'][layer.slot-1]}" stroke-linecap="round">${lines(240,66)}</g>`}if(l.running&&l.beat>=0){const x=l.position/length*1000;grid+=`<path d="M${x} 15V180" stroke="#f1e9b9" stroke-width="1.5"/><path d="m${x-4} 14 4 5 4-5" fill="#f1e9b9"/>`}$('sequence-graph').innerHTML=grid}


function playbackActive(id){if(!state?.playing)return false;if(id==='loop-play')return state.looper.running;if(id==='drums')return state.drums.playing_requested;if(id==='together')return !!state.performance&&state.drums.playing_requested;return !!state.performance}
function togglePlayback(id,start){return playbackActive(id)?command({command:state.tempo.paused?'resume':'pause'}):start()}
function showPlaybackButtons(){const names={'loop-play':'loops',drums:'drums',live:'live performance',together:'live with drums'};for(const [id,name] of Object.entries(names)){const active=playbackActive(id),pause=active&&!state.tempo.paused,b=$(id);b.innerHTML=icon(pause?'pause':id==='together'&&!active?'together':'play');b.classList.toggle('is-playing',pause);b.setAttribute('aria-label',(pause?'Pause ':active?'Resume ':'Play ')+name);b.title=b.getAttribute('aria-label');b.disabled=active&&!!state.looper.record_slot}}
function syncTempoDial(){const bpm=!tempoEditing&&document.activeElement!==$('setting-bpm')&&state?.tempo.transitioning?state.tempo.bpm:Number($('setting-bpm').value);$('tempo-dial').style.setProperty('--angle',(-135+(boundTempo(bpm)-TEMPO_MIN)/(TEMPO_MAX-TEMPO_MIN)*270)+'deg');$('tempo-dial').setAttribute('aria-valuenow',bpm);$('tempo-dial').setAttribute('aria-valuetext',bpm+' BPM')}
function setupTempoDial(){const dial=$('tempo-dial');const value=n=>{$('setting-bpm').value=boundTempo(n);syncTempoDial()};let drag=null;dial.onpointerdown=e=>{tempoEditing=true;drag={y:e.clientY,bpm:Number($('setting-bpm').value)};dial.focus();dial.setPointerCapture(e.pointerId)};dial.onpointermove=e=>{if(drag)value(drag.bpm+(drag.y-e.clientY)/(e.shiftKey?8:2))};dial.onpointerup=()=>{if(drag){drag=null;tempoEditing=false;$('tempo-apply').click()}};dial.onpointercancel=()=>{drag=null;tempoEditing=false;refresh()};dial.onkeydown=e=>{const delta={ArrowRight:1,ArrowUp:1,ArrowLeft:-1,ArrowDown:-1,PageUp:10,PageDown:-10}[e.key];if(delta===undefined&&e.key!=='Home'&&e.key!=='End')return;e.preventDefault();value(e.key==='Home'?TEMPO_MIN:e.key==='End'?TEMPO_MAX:Number($('setting-bpm').value)+delta);$('tempo-apply').click()};$('setting-bpm').oninput=syncTempoDial;syncTempoDial()}
function setupPistilSelector(){const select=$('pistil-preset');const empty=document.createElement('option');empty.value='';empty.textContent='Current patch';empty.disabled=true;select.append(empty);for(let n=1;n<=100;n++){const o=document.createElement('option');o.value=n;o.textContent='Sound '+String(n).padStart(3,'0');select.append(o)}$('pistil-target').onchange=()=>showPistilSelector(true);select.onchange=()=>action(()=>command({command:'layer-preset',slot:Number($('pistil-target').value),preset:Number(select.value)}));$('pistil-editor').onclick=()=>action(()=>command({command:'layer-editor',slot:Number($('pistil-target').value)}))}
async function loadPistilCatalog(){const r=await command({command:'sounds-list'});pistilCatalog=r.sounds;for(let slot=1;slot<=4;slot++){const select=$('layer-sound-'+slot);select.replaceChildren();const current=document.createElement('option');current.value='';current.textContent='Current patch';current.disabled=true;select.append(current);for(const item of pistilCatalog){const option=document.createElement('option');option.value=item.number;option.textContent=String(item.number).padStart(3,'0')+' · '+item.name;option.title=item.description;select.append(option)}}for(const o of $('pistil-preset').options){const item=pistilCatalog.find(x=>x.number===Number(o.value));if(item){o.textContent=String(item.number).padStart(3,'0')+' · '+item.name;o.title=item.description}}}
function showPistilSelector(force=false){if(!state)return;const slot=Number($('pistil-target').value),label=state.instruments.labels[slot-1]||'',match=/^Sound (\d+)$/.exec(label);if(force||document.activeElement!==$('pistil-preset'))$('pistil-preset').value=match?Number(match[1]):'';const entry=pistilCatalog.find(x=>x.number===(match?Number(match[1]):0));$('pistil-description').textContent=entry?entry.description+' '+(entry.kind==='factory'?'Factory settings; edited patches may differ.':''):'';for(const id of ['pistil-preset','pistil-editor'])$(id).disabled=!state.instruments.enabled||!!state.instruments.error}
$('drum-bars').onchange=()=>action(async()=>{const r=await command({command:'drums-length',bars:$('drum-bars').value?Number($('drum-bars').value):null});drumPreviewKey='';return r});
function showDrumSequence(){const seq=state.drums.sequencer;if(!seq)return;if(document.activeElement!==$('drum-bars'))$('drum-bars').value=seq.loop_bars??'';if(state.playing&&seq.running&&seq.document){drawDrumSequence(seq.document,Math.max(0,seq.position-seq.anchor),true);return}const selected=$('beats').value||state.drums.beat;if(!selected)return;const key=selected+'|'+seq.loop_bars;if(key!==drumPreviewKey){drumPreviewKey=key;command({command:'beat-get',beat:selected}).then(r=>{if(drumPreviewKey===key){drumPreview=r.playback_document||r.document;drawDrumSequence(drumPreview,0,false)}}).catch(e=>{drumPreviewKey='';message(e.message,true)})}else if(drumPreview)drawDrumSequence(drumPreview,0,false)}
function xmlText(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function drawDrumSequence(doc,position,running){const length=doc.bars*4,left=145,width=850,row=150/Math.max(1,doc.lanes.length);let svg='';for(let bar=0;bar<=doc.bars;bar++){const x=left+bar/doc.bars*width;svg+=`<path d="M${x} 18V178" stroke="#526f51" stroke-width=".7"/>`;if(bar<doc.bars&&bar%Math.ceil(doc.bars/16)===0)svg+=`<text x="${x+3}" y="11" fill="#b7c69e" font-size="9" font-family="monospace">${bar+1}</text>`}for(const [i,lane] of doc.lanes.entries()){const y=25+i*row;svg+=`<text x="0" y="${y+row/2+3}" fill="#b7c69e" font-family="monospace" font-size="16">${xmlText(lane.name.slice(0,14))}</text><path d="M${left} ${y+row}H995" stroke="#3b5944" stroke-width=".5"/>`;for(const hit of doc.hits.filter(h=>h.lane===lane.id)){let pos=hit.beat;if(Math.floor(pos*4+1e-8)%2)pos+=doc.swing*.25;pos%=length;svg+=`<rect x="${left+pos/length*width}" y="${y+3}" width="${Math.max(2,Math.min(9,width/length*.16))}" height="${Math.max(2,row-6)}" rx="1" fill="${colors[i%4]}" opacity="${lane.muted||!lane.gain?.15:.35+hit.velocity*.65}"/>`}}if(running){const x=left+(position%length)/length*width;svg+=`<path d="M${x} 17V180" stroke="#f1e9b9" stroke-width="2"/>`}$('drum-sequence').innerHTML=svg;const seq=state.drums.sequencer;$('drum-sequence-status').textContent=(running?(state.tempo.paused?'PAUSED':'PLAYING'):'PREVIEW')+' / BAR '+(Math.floor(position%length/4)+1)+' OF '+doc.bars+(seq.pending_beat?' · CHANGE NEXT BAR':'')}

// Studio-wide Space transport: capture both phases so focused controls cannot
// also click, scroll, open a picker, or toggle their checkbox on the same press.
function installStudioSpacebar(target,toggle){
 let down=false;
 const isSpace=e=>e.code==='Space'||e.key===' ';
 const typing=e=>{
  const el=e.target;
  if(el?.isContentEditable||el?.closest?.('textarea,[role="textbox"]'))return true;
  const input=el?.closest?.('input');
  return !!input&&['text','search','email','url','tel','password'].includes(input.type);
 };
 target.addEventListener('keydown',e=>{
  if(!isSpace(e)||e.altKey||e.ctrlKey||e.metaKey||e.isComposing||typing(e))return;
  e.preventDefault();e.stopPropagation();
  if(down||e.repeat)return;
  down=true;toggle();
 },true);
 target.addEventListener('keyup',e=>{
  if(!isSpace(e)||!down)return;
  down=false;e.preventDefault();e.stopPropagation();
 },true);
 target.addEventListener('blur',()=>{down=false;});
}
let studioTransportQueue=Promise.resolve();
function toggleStudioPlayback(){
 studioTransportQueue=studioTransportQueue.then(()=>action(async()=>{
  // Poll once per press: a recent API/robot action or fast double press must
  // toggle the actual transport, not a stale 250ms display snapshot.
  state=await command({command:'status'});
  if(state.looper.record_slot)throw Error('Finish or cancel the take before pausing.');
  if(state.playing)return command({command:state.tempo.paused?'resume':'pause'});
  return loopStart(false);
 }));
 return studioTransportQueue;
}
installStudioSpacebar(window,toggleStudioPlayback);
// End Studio-wide Space transport.


$('key-start').onchange=()=>action(()=>command({...perform($('loop-drums').checked),command:'key-start',enabled:$('key-start').checked}));
