"""Generate the human-readable API and sound maps from runtime metadata."""
from pathlib import Path
from orchid_studio.control_reference import reference, UI_MAP, BEAT_EDITOR
from orchid_studio.catalog import sounds
from orchid_studio.perform import options

ROOT=Path(__file__).resolve().parents[1]
ref=['# Studio control map','',
'Use JSON `POST http://127.0.0.1:8765/command`, or `.venv/bin/orchid-studio request \'{"command":"status"}\'` from the project directory. Responses report `ok`, `queued`, `sent`, or `error`. Read current `status` and `capabilities` first. `queued` needs status/event confirmation; `sent` does not prove sound.',
'', 'The same map is available from `command-help`; filter with `name`. This reference is generated by `scripts/build-control-reference.py` from the runtime catalog.',
'', '## Studio controls', '', '| Control | API | Behavior |','| --- | --- | --- |']
for label,item in UI_MAP.items():ref.append('| '+label+' | '+', '.join('`'+x+'`' for x in item['commands'])+' | '+item['notes']+' |')
ref+=['','## Commands','']
for name,item in reference().items():
 ref+=['### '+name,'',item['description'],'','**Fields:** '+item['parameters'].replace('|',' / '),'','**Behavior:** '+item['behavior'],'']
ref+=['## Drum draft operations','','`beat-edit` takes either `beat` (saved source ID) or `document` (your current draft), plus `action`. It returns `document` and `undo_document`, without changing the library or playback. Call `beat-save` to publish. Bars/steps are 1-based. Keep your own undo stack; draft undo does not overwrite a saved beat until explicitly saved. Browser drafts are tab-local, so API editing does not inspect another unsaved browser draft.','']
for name,desc in BEAT_EDITOR['actions'].items():ref+=['- `'+name+'`: '+desc]
ref+=['','Example: clone a saved beat, then add a kick without overwriting its source:','', '```json','{"command":"beat-edit","beat":"glass-house","action":"clone","new_id":"user-night-drive","name":"Night Drive"}','```','','Use the returned `document` as input for later edits and `beat-save`. For a step, pass `action:"step", lane:"kick", bar:1, step:1, mode:"set", velocity:0.8, probability:1`. To undo, use the last `undo_document`. For full document fields, see the project `docs/DRUM_STUDIO.md`.','',
'## Boundaries and local state','',
'- The Studio API covers its controls and musical effects. Browser navigation, cursor positions, visual rendering, local file saving and unsaved draft history are client operations with the equivalents above.',
'- `layer-editor` opens the Pistil plugin. Individual controls inside the vendor plugin are not Studio API parameters; use Computer Use for them. This audit does not claim full Pistil synthesis-parameter automation.',
'- The API does not expose Orchid firmware/maintenance, sending physical key presses or arbitrary hardware MIDI output. `key-events` only reports key presses Orchid sent. Studio is the clock master.',
'- Six AU slots: loops 1–4, Perform 5, Play Along 6. Mixer keys use `live` for Perform and `play-along` for the direct voice.',
'- Save the complete `loop-export.document` before restarting. Samples and supplied song MIDI live separately under ignored `local/`; exports do not bundle those files.',
'- Set exact physical input and raw chord channel: this device was confirmed Performed 1, Bass 2, Chord 3. Never merge all streams.',
'']
body='\n'.join(ref)
(ROOT/'docs/CONTROL_MAP.md').write_text(body)
folder=ROOT/'skills/orchid-studio-control/references';folder.mkdir(exist_ok=True)
(folder/'control-map.md').write_text(body)

catalog=sounds();opts=options()
lines=['# Sounds and Perform map','',catalog['provenance'],'',
'Descriptions summarize factory configuration, not a listening review. Effects listed are configured effect types, not a claim about their audible mix. User slots and edited patches can differ. This map is available programmatically through `sounds-list` and `perform-options.mode_map`. Source labels/settings: the existing read-only `../orchid_demo/skills/orchid-midi/src/orchid_midi_cli/{presets,factory_voices,parameters}.json` catalog. No hardware commands or archived MIDI captures were used.','',
'## Pistil sound slots','','Select with `layer-preset`, explicit `slot:1–6` and `preset:1–100`. Studio now displays these names in its sound picker.','',
'| Number | Name | Description |','| --- | --- | --- |']
for item in catalog['sounds']:lines.append(f"| {item['number']:03d} | {item['name']} | {item['description']} |")
lines+=['','## Perform modes','','These are Studio software modes, not claims of exact Orchid factory Perform behavior. All follow global BPM.','', '| API ID | Bank | Description |','| --- | --- | --- |']
for id,m in opts['mode_map'].items():
 desc=m['description']
 if 'harmony' in m:desc+=' '+m['harmony']+'. '+m['pitch_rule']+'.'
 lines.append(f"| `{id}` | {m['bank']} | {desc} |")
lines+=['','## Pattern rhythms','','The `pattern` setting matters only when `mode` is `pattern`.','', '| ID | Description |','| --- | --- |']
for id,desc in opts['pattern_descriptions'].items():lines.append(f'| `{id}` | {desc} |')
lines+=['','## Timing, pitch and controls','',
'- `step_beats` controls note division; `.5` is an eighth note, `.25` a sixteenth.',
'- `gate` controls rhythmic note duration; `spread_beats` controls strum/harp width; `harp_octaves`, `slop`, `seed` and `velocity_limit` affect their named functions. Bounds are in `capabilities.settings_schema`.',
'- Melodies and Hooks use the lowest held note as root, with major/minor variants. Orbit, Electric and Anthem default to minor on a single note; the others default to major.',
'- Songs retain the user-supplied snippets. Hold MIDI 60/C4 for source register; other keys transpose. Use `.5` division and gate `1` for source timing. Phrase lengths are exposed in metadata.',
'- The live installed sample catalog is available from `sounds-list.drum_sounds` / `kits-list`: sample name, kit, source path and license. Use `sound-preview` while stopped to audition.','']
(ROOT/'docs/SOUND_PERFORM_MAP.md').write_text('\n'.join(lines))
(folder/'sounds-perform.md').write_text('\n'.join(lines))
print('Generated control and sound maps')
